<?php

namespace StartPack\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{

	public function getConfig()
	{
		$q = $this->createQueryBuilder('c')
			->select('c.key, c.value');
		$req = $q->getQuery();
		$rows = $req->execute();
		foreach ($rows as $key => $value) {
			$tabConfig[$value['key']] = $value['value'];
		}
		 return $tabConfig;
	}

}
